### ISSUE TITLE
Flexelint disable doesn't prevent warning message

### ISSUE THREAD

**Issue by LesnyRumcajs** [jbenden/vscode-c-cpp-flylint#1]
Setting `c-cpp-flylint.flexelint.enable": false` doesn't prevent VS Code from displaying warning _Unable to activate Flexelint analyzer_

Using VS Code 1.13.1, Windows 10.

**Comment by jbenden** [comment]
Hello! Thank you for the bug report! I appreciate the feedback.

I have published a patch version update which should resolve this ticket.

Please re-open if problems persist.
