### ISSUE TITLE
cppcheck errors not displayed on file open

### ISSUE THREAD

**Issue by bbennetts** [jbenden/vscode-c-cpp-flylint#101]
Hi, 

A follow on #98 ; as described I _thought_ cppcheck was not being run on file open, turns out it was.  However, as shown in the lint.txt file attached to that ticket the errors are found, but then the scan (or maybe a second one?) is aborted because 1 != 2.  No errors are displayed in the problems tab.

**Comment by jbenden** [comment]
Hi,

Please try the current `master` branch, as a PR was merged that may have affected you here. Please capture all log output and post if still having problems.

Thanks a ton!
-Joe

**Comment by jbenden** [comment]
A new version of the extension was published. Does it fix the problems you were experiencing?

Thanks,
-Joe

**Comment by bbennetts** [comment]
Hi,

Good news - this issue seems to have been fixed with the new version.  Many thanks for the work!

Bryan.
