### ISSUE TITLE
Error: Skipping CppCheck linter because lintOn 1 is not in 2.

### ISSUE THREAD

**Issue by alecouteurbisson** [jbenden/vscode-c-cpp-flylint#104]
I  am running VSCode on Windows against a Centos 7 target over SSH.  I get the error 
`Skipping CppCheck linter because lintOn 1 is not in 2.` 
and no linter results.  I did look at the source code of the extension to try to figure it out but to no avail.
I would expect the second value in the error message to be 1,3 instead of 2 in which case the error would not happen.
This was working correctly but flatly refuses to work now after much fiddling with the configs and re-installing the extension.

My Workspace settings.json reads:
```
{
    "c-cpp-flylint.enable": true,
    "c-cpp-flylint.debug": true,
    "c-cpp-flylint.clang.enable": false,
    "c-cpp-flylint.cppcheck.enable": true,
    "c-cpp-flylint.flexelint.enable": false
}
```

**Comment by jbenden** [comment]
Hello!

What version are you using? Have you tried the `master` branch?

Also, what user configuration do you have set?

Thanks,
-Joe

**Comment by alecouteurbisson** [comment]
I am using version 1.7.1, installed from within VSCode.  My user config is empty but for the SSH remoting configuration.

**Comment by jbenden** [comment]
I have released version 1.8.0 of the extension. I wonder if a recently fixed bug was the problem...

Please see if the problem continues, and let me know how it goes!

Thanks,
-Joe

**Comment by alecouteurbisson** [comment]
That has fixed the issue thanks.

**Comment by HHPLow** [comment]
Hi @alecouteurbisson 
This question is very strange to me, I use 1.7.1 is ok
But use the same configuration and upgrade to 1.8.0 will meet errors

```text
Performing lint scan of
Skipping CppCheck linter because lintOn 1 is not in 1,3.
Completed lint scans...
Performing lint scan of 
Skipping CppCheck linter because lintOn 2 is not in 1,3.
Completed lint scans...
```

Downgrade to 1.7.1 will be ok
Thanks

**Comment by jbenden** [comment]
It seems like you have a conflict. Please uninstall and reinstall the extension to see if it resolves the problem.

If not, please provide your workspace and user configurations.

Thanks,
-Joe

**Comment by HHPLow** [comment]
Hi Joe:
Uninstall and reinstall didn't work.

Here my configurations
```json
    "c-cpp-flylint.cppcheck.platform": "unix64",
    "c-cpp-flylint.flawfinder.enable": false,
    "c-cpp-flylint.lizard.enable": false,
    "c-cpp-flylint.clang.enable": false,
    "c-cpp-flylint.flexelint.enable": false,
    "c-cpp-flylint.language": "c",
    "c-cpp-flylint.run": "onType",
    "c-cpp-flylint.clang.standard": [
        "posix",
        "c89",
        "c99",
        "c11",
        "c17",
        "c18"
    ],
    "c-cpp-flylint.clang.includePaths": ["${workspaceFolder}/**",
        "/home/user/work/include/**"
    ],
    "editor.formatOnSaveMode": "modifications",
    "c-cpp-flylint.cppcheck.standard": [
        "c89",
        "c99",
        "c11",
    ],
    "c-cpp-flylint.cppcheck.addons": [
        "cert.py",
        "y2038.py",
        "threadsafety.py"
    ],
    "c-cpp-flylint.cppcheck.executable": "/home/user/local/share/cppcheck/cppcheck",
    "c-cpp-flylint.cppcheck.extraArgs": ["--addon=/home/user/local/share/cppcheck/addons/my.json"],
```

Thanks
