### ISSUE TITLE
Unable to get extension working

### ISSUE THREAD

**Issue by WWology** [jbenden/vscode-c-cpp-flylint#105]
I'm still new to programming, and didn't really understand about this error
I have supplied the path for the cppcheck executable correctly and the extension is still giving me parsing error

I'm running Ubuntu 18.04 LTS

vscode-c-cpp-flylint: 'Line could not be parsed: (information) Couldn't find path given by -I '/home/wwology/School/CSCI336/pvs-studio-cmake-examples/include/'' while validating: /home/wwology/School/CSCI336/pvs-studio-cmake-examples/example-1/main.cpp. Please analyze the 'C/C++ FlyLint' Output console. Stacktrace: Error: Line could not be parsed: (information) Couldn't find path given by -I '/home/wwology/School/CSCI336/pvs-studio-cmake-examples/include/'
    at /home/wwology/.vscode/extensions/jbenden.c-cpp-flylint-1.7.1/dist/server/server.bundle.js:21:76004
    at Array.forEach (<anonymous>)
    at o.parseLines (/home/wwology/.vscode/extensions/jbenden.c-cpp-flylint-1.7.1/dist/server/server.bundle.js:21:75738)
    at o.lint (/home/wwology/.vscode/extensions/jbenden.c-cpp-flylint-1.7.1/dist/server/server.bundle.js:21:75641)
    at /home/wwology/.vscode/extensions/jbenden.c-cpp-flylint-1.7.1/dist/server/server.bundle.js:138:6802
    at Array.forEach (<anonymous>)
    at /home/wwology/.vscode/extensions/jbenden.c-cpp-flylint-1.7.1/dist/server/server.bundle.js:138:6758
    at Generator.next (<anonymous>)
    at s (/home/wwology/.vscode/extensions/jbenden.c-cpp-flylint-1.7.1/dist/server/server.bundle.js:138:2924)

**Comment by jbenden** [comment]
Hello,

It looks like a path was specified, but does not exist on your file-system:

```
/home/wwology/School/CSCI336/pvs-studio-cmake-examples/include/
```

Hopefully fixing this problem, by creating it or removing it from the configuration, will help!
-Joe
