### ISSUE TITLE
Disable linting for header files

### ISSUE THREAD

**Issue by mirkow** [jbenden/vscode-c-cpp-flylint#106]
Is there a way to disable linting for header or, more generic, a blacklist (supported regex) for disabling linting for some files?

The linting of headers produces thousands of errors on my system since it also considers the system files. The linting of source works as they should.

P.S. Thanks for developing the plugin! It makes linting with PCLP a lot less time consuming.

**Comment by jbenden** [comment]
Hi,

There is a way for specifying your file set. It's inside the C/C++ extension of VSCode. It ends up opening a file named `c_cpp_properties.json`. Inside of this file, one may specify the files to include and exclude from one's workspace. It may also be set inside the settings UI of VSCode.

I had an example, but I'm not sure where it is right now - sorry. You'll need to research the VSCode documentation.

Best regards,
-Joe

**Comment by mirkow** [comment]
Thanks for the answer, but I cannot find a way to make that work. For exclusion I only found the setting "files.exclude", but it still produces error in this folders when linting headers. Also I dont want to exclude headers from the whole project in VSCode but only from linting.

**Comment by jbenden** [comment]
Hi,

To handle only headers, or certain files, you'll need to use `...extraArgs` and the proper parameters for the linter(s) giving troubles.

Otherwise, I'd say to research the use of `c_cpp_properties.json` of the `ms-vscode.cpptools` extension: https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp

-Joe
