### ISSUE TITLE
Activate only a set of linters

### ISSUE THREAD

**Issue by mirkow** [jbenden/vscode-c-cpp-flylint#107]
I regularly get a popup in VS Code saying "Unable to activate Lizard analyzer" and "Unable to activate FlawFinder analyzer", which is a little annoying.
Is there a way to only activate a specific set of linters? (I only want to use PCLP for example).

**Comment by jbenden** [comment]
Hello,

There are configurable properties for enabling and disabling the various supported linters. This should help you achieve the desired goal you are after.

Best regards,
-Joe

**Comment by mirkow** [comment]
Thanks, that solved it. Dunno why they were activated in the first place.
