### ISSUE TITLE
Error: Will not analyze an untrusted workspace.

### ISSUE THREAD

**Issue by Hadatko** [jbenden/vscode-c-cpp-flylint#112]
No such an option in my workspace: ![image](https://user-images.githubusercontent.com/13130700/112116216-5586af00-8bba-11eb-9f1a-13d029bba961.png)
Issue with version 1.9.0:
![image](https://user-images.githubusercontent.com/13130700/112116275-67685200-8bba-11eb-80ae-3af0616d6031.png)

**Comment by jbenden** [comment]
It's inside the command palette and/or the dialog shown at start of opening the workspace/folder.

**Comment by Hadatko** [comment]
Am i looking on wrong place?
![image](https://user-images.githubusercontent.com/13130700/112172572-1de92880-8bf5-11eb-9f59-5c7f4a6f61d0.png)

**Comment by jbenden** [comment]
Yes. The keybinding on Linux is `Shift+Ctrl+P` for the command palette.

**Comment by Hadatko** [comment]
That help, but unfortunately since version 1.8.2 i am getting error Skipping analysis because 1 !== 2.
I will create new jira.

**Comment by Hadatko** [comment]
Thank you for this one.

**Comment by dzid26** [comment]
**Incoming request for isTrusted property. Have false**

This ^^ is for google to index the string so people like me who don't read instructions can search for it. 

Summarizing again:
If you are getting: `Incoming request for isTrusted property. Have false.`, that means you need to enable trust for the workspace from the [command palette](https://github.com/jbenden/vscode-c-cpp-flylint/blob/9c17a2e65f981c2b69790ecfd172648851675964/package.json#L119):
 
![image](https://user-images.githubusercontent.com/841061/115161037-5c91c780-a069-11eb-92ea-3971848cdf66.png)
