### ISSUE TITLE
Release on Open-VSX?

### ISSUE THREAD

**Issue by jerabaul29** [jbenden/vscode-c-cpp-flylint#114]
Could you release this extension also on Open-VSX so that other projects also can use it? (See for example https://github.com/onivim/oni2/issues/3357 ) .

**Comment by jbenden** [comment]
Hello,

I have mostly completed this task, and am only waiting on taking ownership of the "jbenden" namespace. However, this doesn't preclude the use of the extension now available on Open-VSX.

- [X] Create Eclipse account.
- [X] Create Open-VSX account.
- [X] Add token to the GitHub Action.
- [X] Publish/deploy to both marketplaces.
- [ ] Claim ownership of `jbenden` publisher.

https://open-vsx.org/extension/jbenden/c-cpp-flylint

**Comment by jbenden** [comment]
Thanks!
