### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by dwarning** [jbenden/vscode-c-cpp-flylint#115]
Hello,
I think I made everything right as the installation guide offers.

But here I am lost - I want make a static analysis:

Development Setup
run _npm install_ inside the project root

I generated a package.json file with
npm init -y
without this I got lot of warnings in npm install next

_npm install_ created a lockfile as package-lock.json

_Developing the Server_ <----- why developing a server?
_open VS Code rooted inside the project root._ <---- what means rooted? admin rights? or to start in the project folder?
run _cd server && npm run test && cd .._ to execute the unit-tests for all linters.

If I gave this command after starting vs code the answer is clear: no folder server available

I am missing a simple button or menu entry to start the lint, e.g. cppcheck or clang which all are working separate.

**Comment by jbenden** [comment]
Hello,

The documentation snippet you've posted is for developing the extension itself.

If you are looking for information on using the extension, then:

1. Install the extension through the normal extension panel within VS Code. Search for "C/C++ Flylint" and click the install button.
2. After installation, go to the user and/or workspace settings and narrow into the extensions' settings.
3. From the extensions settings, enable/disable linters you wish to use.
4. (optional depending on linter) Configure linter specific settings. This is the part which can and is difficult sometime, but having a linter work from the command-line will immensely help with this part!

**Comment by dwarning** [comment]
Thanks Joseph,
so I was total wrong with my development settings.
No I have enabled cppcheck and clang in the extension settings all in default.
But question remains how can I make a check for only one file or for the entire code folder.
We have in the settings:
C-cpp-flylint: Run
onSave
but if I open one file and make a save noting happens.
Can I make a check w/o save?
Kind Regards,
Dietmar

**Comment by jbenden** [comment]
> Can I make a check w/o save?

Depends on the linter, but mostly no. Nearly all require a full project, with a root folder, and configuration of some sort.

**Comment by dwarning** [comment]
OK - found it out.
CTRL + Shift + P comes to the tools and command Menu.
Toggle the Flylint Trust flag
Sorry  - I am VS Code beginner. 
Perhaps a Usage section in github readme would help.
Thank you again,
Dietmar

**Comment by jbenden** [comment]
Thanks!
