### ISSUE TITLE
Vscode with clang but dont know how to use C/C++ advanced lint

### ISSUE THREAD

**Issue by OrdinaryChen** [jbenden/vscode-c-cpp-flylint#120]
I work with Vscode on ubuntu, and down clang with apt-get install, but this plug dose not work , and nothing happen to my code.....I dont know how to use C/C++ advanced lint....anyone can help me??

**Comment by Cygon** [comment]
I am having the same problem. My system has GCC and clang in the standard search paths. I use VSCodium and just installed + enabled this extension. Now what?

There doesn't seem to be anything automatic happening in the background, no new buttons and the documentation doesn't mention how to run a static analysis, whether it runs automatically and if it runs, how/where the results are presented.

**Comment by OrdinaryChen** [comment]
problem solved，anwser is leave s**t vscode along and use f**king awsome CLion

**Comment by OrdinaryChen** [comment]
problem solved，anwser is leave vscode away and use awsome CLion

**Comment by Cygon** [comment]
Not an option for me. I stongly dislike CLion and the other subscription-licensed JetBrains products. Also: Java.

**Comment by MoshePerez** [comment]
I had the same problem, Running "C/C++ Flylint: Toggle Workspace Trust Flag" in the command palette solved it for me.

**Comment by Cygon** [comment]
@MoshePerez I already have this workspace set as trusted.

How do you notice that the extension is active? I have no new panels, no extra info in the gutter lines, no new project configuration options, absolutely nothing added or changed as far as I can tell...

**Comment by MoshePerez** [comment]
@Cygon My workspace was already set as trusted also. I had to run it anyway, specifically for this extension.

**Comment by jbenden** [comment]
This project is a proxy for multiple source code static analysis tools. It does not have much configuration.

A union of all tools is required. There *is much configuration* with compilers and the analysis tools.
