### ISSUE TITLE
Version 0.3.0 broke the problems output

### ISSUE THREAD

**Issue by JimStar** [jbenden/vscode-c-cpp-flylint#13]
Commit [948f210d77db26146e6ff23be3cbd5f5a54b6acf](https://github.com/jbenden/vscode-c-cpp-flylint/commit/948f210d77db26146e6ff23be3cbd5f5a54b6acf) has introduced the "`tmpFileName`", and now the problems output is crypted like this:
`'In file included from /var/folders/8f/107k_1z120564m__892q2pr00000gn/T/tmp-58719JxpJIjohOdwQ.tmp:1:'`
instead of mentioning the real project's file-name...

Here is a screenshot:
<img width="1388" alt="screen shot 2017-10-15 at 11 56 04" src="https://user-images.githubusercontent.com/3421219/31580016-64b8b75e-b1a0-11e7-8fe7-f01600672c80.png">

**Comment by jbenden** [comment]
Thank you for the report. I have published a patch update, to resolve this bug.
