### ISSUE TITLE
Getting "Incoming request for isTrusted property. Have false." on trusted workspace

### ISSUE THREAD

**Issue by JSurf** [jbenden/vscode-c-cpp-flylint#130]
This is NOT a duplicate of #112 

My workspace is trusted, but I still get:
Incoming request for isTrusted property. Have false.
Will not analyze an untrusted workspace.

I work with a ssh remote workspace, but also tried a local workspace and a WSL Ubuntu workspace, all with the same result even they are all trusted

![image](https://user-images.githubusercontent.com/1379596/127866362-e2c3a6b3-bc86-43e7-99a4-0258f8102ac5.png)

Using release 1.9.3 and vscode version 1.58.2

Any Idea on how to get this extension to recognize the trusted state correctly

**Comment by jbenden** [comment]
Hi,

I see you've marked the actual VS Code as trusted; however, did you also mark the C/C++ project as trusted? Under Ctrl+Shift+P and "C/C++ Flylint: Toggle Workspace Trust" or similar?

I know that sounds silly, but there's a transition period going on with this whole trusted folder thing...

Thanks,
-Joe

**Comment by JSurf** [comment]
That did the trick, thanks

**Comment by jbenden** [comment]
Fixed in 1.10.0.

Thanks!
