### ISSUE TITLE
"Unable to activate Flexelint analyzer." prompt, but actually it works.

### ISSUE THREAD

**Issue by ravenxrz** [jbenden/vscode-c-cpp-flylint#132]
Every time I open vscode, this prompt shows up.

![image](https://user-images.githubusercontent.com/44746032/128652736-61c44239-de20-4ca8-a179-8f18956b7eb7.png)

But I think it's active( like the code below).  Did I miss something or it's a bug?

![image](https://user-images.githubusercontent.com/44746032/128652790-f17ed192-021c-47be-b6c3-c62573fbddde.png)

**Comment by jbenden** [comment]
Hi! It's not a bug. This extension supports multiple analyzers, for which you seem to have Clang working.

If you do not have Flexelint, then I'd say to disable that portion. You may do so in the settings for the extension...

Best Regards,
-Joe

**Comment by ravenxrz** [comment]
> Hi! It's not a bug. This extension supports multiple analyzers, for which you seem to have Clang working.
> 
> If you do not have Flexelint, then I'd say to disable that portion. You may do so in the settings for the extension...
> 
> Best Regards,
> -Joe

 😂, my bad. Thank you for your reply.

**Comment by huangyanxiong01** [comment]
How disable flexelint analyzer? I don't find about flexelint analyzer option

**Comment by niVelion** [comment]
> How disable flexelint analyzer? I don't find about flexelint analyzer option

The setting id is `c-cpp-flylint.flexelint.enable`.
