### ISSUE TITLE
c-cpp-flylint.clang.standard should allow c++2b or c++23

### ISSUE THREAD

**Issue by Wongboo** [jbenden/vscode-c-cpp-flylint#137]
**c-cpp-flylint.clang.standard** should allow c++2b or c++23

**Comment by jbenden** [comment]
Hi,

The setting should be possible to have these values, is it not? Or do you mean the documentation text should list these values?

Thanks!
-Joe

**Comment by jbenden** [comment]
Any value should be permitted in the settings, providing the tools in question also support such value.
