### ISSUE TITLE
Can only go to the outmost file from reported problems

### ISSUE THREAD

**Issue by JimStar** [jbenden/vscode-c-cpp-flylint#14]
The problem report of nested issues has all the nested files-linenumbers in one report-line. Because of that you can only go to the outmost file when clicking this problem-line, and no way do directly go to inner-most file's line containing the issue reported.

Here is the screenshot:
<img width="1279" alt="screen shot 2017-10-15 at 12 57 07" src="https://user-images.githubusercontent.com/3421219/31580349-4197ff38-b1a9-11e7-9fc8-568a11a2cd72.png">

When this line is clicked, I go to TranslatorBase.cpp line 1. And no way to go to TranslatorBase.h. line 1 column 9 - the one containing the issue itself...

PS. Wow, you are fast! Thank you for such a quick fix of the previous issue.

**Comment by jbenden** [comment]
I'm not sure how to have it jump to the other file. Do you know of an extension that does, or did? I may be able to figure it out then...

Thanks!
-Joe

**Comment by jbenden** [comment]
Thank you for the PR - it made it clear to me what I had overlooked.  I did not realize that multiple diagnostics could be sent for files that were not directly opened.

I have published an updated version that incorporates all fixes thus far. Please let me know if you experience any further troubles!

Again, thank you so much,
-Joe
