### ISSUE TITLE
Nested file diagonstics disappears after closing the nested file

### ISSUE THREAD

**Issue by JimStar** [jbenden/vscode-c-cpp-flylint#16]
Thank you for 0.4 quick-fix release, it made diagnostics much more mature!

Now one more issue with it. How to reproduce:
- Open some .cpp file having some issues and having included files with their own issues.
-  Now you see two separate files' issue-reports in "Problems" panel. So far so good.
- Click on one of the issues reported for the a nested file.
- The nested file is correctly opened and the cursor goes to correct place of the clicked issue.
- Now close this nested file.
- The nested file's reported issues block disappears from the "Problems" panel, and only the initial file's block remains. So, now we see the report that the file included from particular place has some issues, but the issues themselves of this nested file are gone from the panel. Now the info is not complete: we see that there are some issues in the included file, we can navigate the place where it is included, but we don't see the issues themselves and can't quickly navigate to them.
- Of course, if we change and re-save the initial file, the nested file's issues re-appear again...

**Comment by jbenden** [comment]
Hello! Thank you for the excellent bug report.

I have release version 0.4.1, which should resolve this bug report.

Thank you, again!
-Joe
