### ISSUE TITLE
Build vscode extension error

### ISSUE THREAD

**Issue by toanpi** [jbenden/vscode-c-cpp-flylint#161]
I'd like to build this extension for personal usage. But I got these below error.
Does any one know how to fix it ? 
Many Thank!

`
PS C:\working\project\tp-static-analysis-c-c-> vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> c-cpp-flylint@1.11.0 vscode:prepublish
> npm run webpack

> c-cpp-flylint@1.11.0 webpack
> npm run clean && webpack --mode production --config ./client/webpack.config.js && webpack --mode production --config ./server/webpack.config.js

> c-cpp-flylint@1.11.0 clean
> rimraf client/out && rimraf server/out && rimraf specs/out

C:\working\project\tp-static-analysis-c-c-\client\node_modules\ts-loader\dist\after-compile.js:19
        if (compilation.compiler.isChild()) {
                        ^

TypeError: Cannot read properties of undefined (reading 'compiler')
    at C:\working\project\tp-static-analysis-c-c-\client\node_modules\ts-loader\dist\after-compile.js:19:25
    at C:\working\project\tp-static-analysis-c-c-\client\node_modules\ts-loader\dist\instances.js:216:93
    at Hook.eval [as call] (eval at create (C:\working\project\tp-static-analysis-c-c-\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\working\project\tp-static-analysis-c-c-\node_modules\webpack\node_modules\tapable\lib\Hook.js:14:14)
    at C:\working\project\tp-static-analysis-c-c-\node_modules\webpack\lib\Compilation.js:3063:40
    at eval (eval at create (C:\working\project\tp-static-analysis-c-c-\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:17:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.8.0
 ERROR  npm failed with exit code 1
`

**Comment by jbenden** [comment]
I'd try Node.js v12 or so... I do not think that 17 is used inside VSCode, yet.

**Comment by jbenden** [comment]
Did you get past this bug report? Given the other report (#162), I think you may have...

Thanks,
-Joe

**Comment by toanpi** [comment]
Thank @jbenden ,
I solved this error by updating latest version for almost packages.
