### ISSUE TITLE
 C/C++ FlyLint version 1.12.0: Line could not be parsed: Error: encoding error while validating

### ISSUE THREAD

**Issue by burstchao** [jbenden/vscode-c-cpp-flylint#173]
my os is windows11;and when i use C/C++ FlyLint version 1.12.0 it make a error:
lease analyze the 'C/C++ FlyLint' Output console. Stacktrace: Error: Line could not be parsed: Error: encoding error in g:\xxx\xxxx.cpp
    at c:\Users\Charles\.vscode\extensions\jbenden.c-cpp-flylint-1.12.0\server\out\server.js:2:39162
    at Array.forEach (<anonymous>)
    at s.parseLines (c:\Users\Charles\.vscode\extensions\jbenden.c-cpp-flylint-1.12.0\server\out\server.js:2:38911)
    at s.lint (c:\Users\Charles\.vscode\extensions\jbenden.c-cpp-flylint-1.12.0\server\out\server.js:2:38814)
    at c:\Users\Charles\.vscode\extensions\jbenden.c-cpp-flylint-1.12.0\server\out\server.js:2:48378
    at Array.forEach (<anonymous>)
    at L (c:\Users\Charles\.vscode\extensions\jbenden.c-cpp-flylint-1.12.0\server\out\server.js:2:48353)
    at async c:\Users\Charles\.vscode\extensions\jbenden.c-cpp-flylint-1.12.0\server\out\server.js:2:51467

**Comment by burstchao** [comment]
i found it will be error when i enable FlawFinder or lizard

**Comment by rei-vilo** [comment]
Same issue here, when `CppCheck` and `lizard` are enabled.

**Comment by jbenden** [comment]
Hi,

The problem is most certainly that your machine is NOT in a UTF-8 locale. I'd suggest ensuring it so Python operates in UTF-8 mode.

There is no perfect solution to the problem, either. I could possibly add a hack to "attempt" native locale, but even that could fail.... :shrug: 

Best regards,
-Joe

**Comment by burstchao** [comment]
![image](https://user-images.githubusercontent.com/36848799/194794890-07d7124d-68ef-4b6d-bb10-4b49a678609e.png)

my Python operates is in UTF-8 mode,but my machine file save encode mode I can`t not sure

**Comment by rei-vilo** [comment]
> The problem is most certainly that your machine is NOT in a UTF-8 locale. I'd suggest ensuring it so Python operates in UTF-8 mode.

Thank you for the pointer. 

It happens both `python2` and `python3` were installed on my PC. `python2` was configured with `ascii` and `python3` with `UTF-8`. 

Setting `python3` as default removed the issue.

So the case is solved for me.

**Comment by burstchao** [comment]
> 


my pc just install python3,it make me confused

**Comment by pnrao** [comment]
I had this problem too. Seeing lizard mentioned above, I checked my computer and found out that lizard was not running properly.

Running these two commands (in zsh) fixed it for me.

```$ for i in `pip list -u --user --format json|jq '.[].name' -r` ; { pip install --user -U $i }```

```$ pip install --user lizard```

Just the first command should have fixed it, but I don't know why, the second command was needed too.
