### ISSUE TITLE
Release version can't parse c_cpp_properties.json - JSON5 import issue

### ISSUE THREAD

**Issue by dzid26** [jbenden/vscode-c-cpp-flylint#180]
```
Could not find or parse the workspace c_cpp_properties.json file; continuing...
TypeError: n(...).parse is not a function
    at O (c:\Users\dzidm\.vscode\extensions\jbenden.c-cpp-flylint-1.12.1\server\out\server.js:2:44921)
    at async Function.L (c:\Users\dzidm\.vscode\extensions\jbenden.c-cpp-flylint-1.12.1\server\out\server.js:2:46799)
```
This error is for the version from the marketplace or packaged locally using with `npm run compile && vsce package` from the latest commit or release commit.  In debug mode (F5) the problem is NOT happening!

**Comment by jbenden** [comment]
I suspect you have a bad development environment. Please fully recreate (and ensure caches don't interfere). If you still experience problems, let me know!

Best regards,
-Joe

**Comment by dzid26** [comment]
I was able to narrow it down to this (**my own**) commit https://github.com/jbenden/vscode-c-cpp-flylint/commit/2292ee293dd652d0a723a9a88f0c2d8575bdf482. 

Did I import JSON5 incorrectly? 

- I tried moving it to imports at the top of the file `import JSON5 = require('json5');`, but it didn't help:
```
TypeError: _.parse is not a function
    at N (c:\Users\dzidm\.vscode\extensions\jbenden.c-cpp-flylint-1.12.1\server\out\server.js:2:18495)
    at async Function.B (c:\Users\dzidm\.vscode\extensions\jbenden.c-cpp-flylint-1.12.1\server\out\server.js:2:20366)
Could not find or parse the workspace c_cpp_properties.json file; continuing...
```
- Importing [as ](https://github.com/json5/json5#modules)`import JSON5 from 'json5'` gives me linter error: `Module '"json5"' has no exported member 'JSON5`

Or could it be related to this https://stackoverflow.com/questions/71586851/typeerror-json5-parse-is-not-a-function?
Someone said it's some VScode issue.

**Comment by jbenden** [comment]
Try the import at the top of the file as:

```
import { parse as jsonParse } from 'json5';
```

And also edit the usage line from `JSON5.parse` to `jsonParse`.

**Comment by dzid26** [comment]
Unfortunately, this produces the same error:
```
Could not find or parse the workspace c_cpp_properties.json file; continuing...
TypeError: _.parse is not a function
    at N (c:\Users\dzidm\.vscode\extensions\jbenden.c-cpp-flylint-1.12.1\server\out\server.js:2:18495)
    at async Function.B (c:\Users\dzidm\.vscode\extensions\jbenden.c-cpp-flylint-1.12.1\server\out\server.js:2:20366)
```

**Comment by Mpic** [comment]
I just installed and tested this extension and I get the same error...
```
Could not find or parse the workspace c_cpp_properties.json file; continuing...
TypeError: r.parse is not a function
    at N (c:\Users\user\.vscode\extensions\jbenden.c-cpp-flylint-1.13.0\server\out\server.js:2:18495)
    at async B (c:\Users\user\.vscode\extensions\jbenden.c-cpp-flylint-1.13.0\server\out\server.js:2:20366)
    at async c:\Users\user\.vscode\extensions\jbenden.c-cpp-flylint-1.13.0\server\out\server.js:2:24847
```

**Comment by dzid26** [comment]
Since the problem doesn't appear when debugging, I turned off [minification](https://github.com/jbenden/vscode-c-cpp-flylint/blob/2d5699303e7b069b940fa2cb09fd6bfe3f687a9c/package.json#L46):
`"webpack": "npm run clean && webpack  --config ./client/webpack.config.js && webpack --config ./server/webpack.config.js",`
so that the error function can be seen properly. 

After that I compiled it with `vsce package` and installed.

Now I am getting:
```
Could not find or parse the workspace c_cpp_properties.json file; continuing...
TypeError: JSON5.parse is not a function
    at getCppProperties (c:\Users\dzidm\.vscode\extensions\jbenden.c-cpp-flylint-1.13.0\server\out\server.js:198:42)
    at async Function.validateTextDocument (c:\Users\dzidm\.vscode\extensions\jbenden.c-cpp-flylint-1.13.0\server\out\server.js:377:20)
```
And here is the Javascript [file](https://github.com/jbenden/vscode-c-cpp-flylint/files/12307036/server.zip):

So it compiles to something very similar that we had one commit earlier https://github.com/jbenden/vscode-c-cpp-flylint/blame/78c48ffe0a27111ba731e2f930b99d56cde8e566/server/src/server.ts#L235-L236

I don't know what is wrong with calling JSON5.parse().

Seems like there is more talk regarding webpack thingy https://github.com/microsoft/vscode/issues/130367
Also https://github.com/electron/electron/issues/21457#issuecomment-1667909379.

I don't know if this is the problem here. I was under the impression that some people don't experience this.

**Comment by dzid26** [comment]
Ok, I fixed it but it is dumb.

Based on [this](https://github.com/json5/json5/issues/240#issuecomment-1050620362) I created [index.mjs.d](https://github.com/jbenden/vscode-c-cpp-flylint/files/12307627/index.mjs.d.zip) in `vscode-c-cpp-flylint\node_modules\json5\dist`

Then replaced:
https://github.com/jbenden/vscode-c-cpp-flylint/blob/2d5699303e7b069b940fa2cb09fd6bfe3f687a9c/server/src/server.ts#L5
with 
`import JSON5 from 'json5/dist/index.mjs'`
And
https://github.com/jbenden/vscode-c-cpp-flylint/blob/2d5699303e7b069b940fa2cb09fd6bfe3f687a9c/server/src/server.ts#L236
with 
`const cCppProperties: IConfigurations = JSON5.parse((fs.readFileSync(cCppPropertiesPath, 'utf8')));`

Then run `vsce package` and installed. 

Here is compiled [vsix](https://github.com/jbenden/vscode-c-cpp-flylint/files/12307666/c-cpp-flylint-1.13.0.working.zip)

**Comment by user32dll** [comment]
> 

that vsix seems to do the job for me. cheers man

**Comment by leoboschiazzo** [comment]
Same issue here. Windows 10 64 bits clean install, not working

![image](https://github.com/jbenden/vscode-c-cpp-flylint/assets/109548660/06507fe7-d1f8-4fd3-9e55-695616cde57c)

![image](https://github.com/jbenden/vscode-c-cpp-flylint/assets/109548660/96596dc9-c41a-47e1-9745-b05d656deb21)

![image](https://github.com/jbenden/vscode-c-cpp-flylint/assets/109548660/1844675e-d4ce-487c-b6c9-860f313839af)

**Comment by wangling12** [comment]
Same error,and vsix work for me.
Maybe create a pr to fix it?

**Comment by lemonkey** [comment]
Please include this in an official release 👍

**Comment by dzid26** [comment]
I've got annoyed with this issue again. But I think I found a better solution that can be integrated - https://github.com/jbenden/vscode-c-cpp-flylint/pull/217 
In the meantime, here is a packaged extension based on latest version [c-cpp-flylint-1.14.0.vsix.zip](https://github.com/jbenden/vscode-c-cpp-flylint/files/15002393/c-cpp-flylint-1.14.0.vsix.zip)

**Comment by jbenden** [comment]
A commit was made to resolve this matter. It is pending release, though.
