### ISSUE TITLE
Error: Line could not be parsed

### ISSUE THREAD

**Issue by vvzvlad** [jbenden/vscode-c-cpp-flylint#19]
When I try to view the extension log, I see such notifications:
`An exception occurred in CppCheck while parsing output for file /Users/vvzvlad/Documents/Unwired/contiki_ud_ng/unwired/ud_binary_protocol.h stacktrace: Error: Line could not be parsed: Defines: CURRENT_DEVICE_VERSION=1;BIG_VERSION=1;LITTLE_VERSION=1;CURRENT_DEVICE_GROUP=1;CURRENT_DEVICE_SLEEP_TYPE=1;CURRENT_ABILITY_1BYTE=1;CURRENT_ABILITY_2BYTE=1;CURRENT_ABILITY_3BYTE=1;CURRENT_ABILITY_4BYTE=1;CLASS=1;CLASS_B=1;CLASS_C=1;IF_UD_RELAY=1;PRIu32="u";PRIx32="x";PRIX32="X";PRIXX32="X";NETSTACK_CONF_WITH_IPV6=1`

It is important? Is it worth anything to do with them?

[log.txt](https://github.com/jbenden/vscode-c-cpp-flylint/files/1402225/log.txt)
[config.txt](https://github.com/jbenden/vscode-c-cpp-flylint/files/1402228/config.txt)

**Comment by jbenden** [comment]
Hello,

An update has been published to resolve this matter.

Thank you!
-Joe
