### ISSUE TITLE
"onType" and "onSave" not working as expected

### ISSUE THREAD

**Issue by bensetterholm** [jbenden/vscode-c-cpp-flylint#2]
When the setting `"c-cpp-flylint.run": "onSave"` is set, the linter squiggles do not update unless I close the file and reopen it again.  The setting `"c-cpp-flylint.run": "onType"` updates the squiggles only whenever I save.

With the `onType` setting on, the output console *does* output

    Performing lint scans...
    Completed lint scans...

etc., whenever I type.  With the `onSave` setting, the console only prints the above messages when I open a file, and not when I save.

I am using VS Code 1.13.1 on macOS Sierra if that helps.

**Comment by jbenden** [comment]
The fix will be incorporated within the next release.
