### ISSUE TITLE
New version will parse errors in MinGW-w64 headers

### ISSUE THREAD

**Issue by imba-tjd** [jbenden/vscode-c-cpp-flylint#20]
Hi. My VSC version is 1.17.2, cppflylint version is 0.5.1, OS version is Windows 1709.
I installed Clang 5.0.0 and MinGW-w64 7.1.0, and merged them into one directory. A few days ago (I guess after you released 0.5.0) I encountered this problem.
![image](https://user-images.githubusercontent.com/24759802/31926731-fee8f2ca-b8c2-11e7-9e45-615365409946.png)

When I double click one of the entry, it will show a `can not find file` error.
![image](https://user-images.githubusercontent.com/24759802/31926872-e64b569e-b8c3-11e7-8a4a-70f1eced00c3.png)

Here is part of my settings.json
```json
"c-cpp-flylint.cppcheck.enable": false,
"c-cpp-flylint.flexelint.enable": false,
"c-cpp-flylint.run": "onType",
"c-cpp-flylint.clang.includePaths": [
    "${workspaceRoot}",
    "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include/c++",
    "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include/c++/x86_64-w64-mingw32",
    "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include/c++/backward",
    "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include",
    "C:/llvm/include",
    "C:/llvm/x86_64-w64-mingw32/include",
    "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include-fixed"
],
"c-cpp-flylint.clang.defines": [
    "_DEBUG",
    "UNICODE",
    "__GNUC__=7",
    "__cdecl=__attribute__((__cdecl__))"
],
"c-cpp-flylint.standard": [
    "c11",
     "c++1z"
]
```

Here is my c_cpp_properties.json (I have disabled `cpptools`'s lint)
```json
{
    "configurations": [
        {
            "name": "Win32",
            "intelliSenseMode": "clang-x64",
            "includePath": [
                "${workspaceRoot}",
                "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include/c++",
                "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include/c++/x86_64-w64-mingw32",
                "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include/c++/backward",
                "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include",
                "C:/llvm/include",
                "C:/llvm/x86_64-w64-mingw32/include",
                "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include-fixed"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "__GNUC__=7",
                "__cdecl=__attribute__((__cdecl__))"
            ],
            "browse": {
                "path": [
                    "C:/llvm/x86_64-w64-mingw32/include",
                    "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include",
                    "C:/llvm/lib/gcc/x86_64-w64-mingw32/7.1.0/include-fixed",
                    "C:/llvm/include/*",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```

Besides, `c-cpp-flylint.standard` seems not work? I can still see some errors like `long long is incompatible with c++ 98`.

Thank you.

**Comment by jbenden** [comment]
Hello,

There seems to be a number of problems going on.

- The message from Clang about `long long is incompatible with c++ 98` is a verbose analysis message that is unrelated to the VS Code extension.
- A few of the Clang message may be silenced with the following configuration snippet:

```
    "c-cpp-flylint.clang.warnings": [
        "no-c++98-compat",
        "no-c++98-compat-pedantic",
        "no-reserved-id-macro"
    ]
```

I do not have experience with Clang mixed with Mingw64. I am therefore unable to help debug this configuration - maybe elsewhere on the net could assist in completely configuring it?

Best Regards,
-Joe

**Comment by imba-tjd** [comment]
Fine. I recently noticed clang 5.0.0 would somehow crash on my computer(just like below). Maybe when this happeds, cppflylint happend record those unmeaningful message. Anyway, thank you for your help.

![image](https://user-images.githubusercontent.com/24759802/32442847-c687d30e-c337-11e7-9ecc-5bdb8b1d600c.png)
