### ISSUE TITLE
Is there anyway to find include path with compile_commands.json?

### ISSUE THREAD

**Issue by ywq1113** [jbenden/vscode-c-cpp-flylint#213]
I found this question, and I have met the same problem. https://github.com/jbenden/vscode-c-cpp-flylint/issues/106
I also search help from here https://github.com/jbenden/vscode-c-cpp-flylint/blob/main/package.json. But could not find a way to resolve my problem.

P.S. Thanks for developing the plugin!

**Comment by jbenden** [comment]
Not at this time, please use `c_cpp_properties.json` instead.
