### ISSUE TITLE
Parsing errors in Mingw64 headers

### ISSUE THREAD

**Issue by DickSteelOy** [jbenden/vscode-c-cpp-flylint#26]
Visual Studio Code: 1.20.0
C/C++ Advanced Lint: 0.5.4
C/C++: 0.14.6

Windows 10 Pro: 1709
Clang: 5.0.1.0

settings.json:
    
    "git.ignoreMissingGitWarning": true,
    "C_Cpp.errorSquiggles": "Disabled",
    "c-cpp-flylint.clang.enable": true,
    "c-cpp-flylint.cppcheck.enable": false,
    "c-cpp-flylint.flexelint.enable": false,
    "c-cpp-flylint.run": "onType",
   
    "c-cpp-flylint.debug": true,
    "c-cpp-flylint.standard": [
        "c++11",
    ],

    "c-cpp-flylint.includePaths":  [
        
        "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++",
        "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/x86_64-w64-mingw32",
        "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/backward",
        "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include",
        "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include-fixed",
        "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/include"
        
    ],
    
c_cpp_properties.json:

            "name": "Mingw64",
            "intelliSenseMode": "clang-x64",
            "includePath": [
                "${workspaceRoot}",
                "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++",
                "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/x86_64-w64-mingw32",
                "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/backward",
                "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include",
                "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include-fixed",
                "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "__GNUC__=7",
                "__cdecl=__attribute__((__cdecl__))"
            ],
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++",
                    "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/x86_64-w64-mingw32",
                    "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/backward",
                    "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include",
                    "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include-fixed",
                    "C:/Software/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            

So this is what will show up after adding a header, and even with an obvious coding error, I do not get error squiggles:

![2018-02-13 3](https://user-images.githubusercontent.com/36000427/36172715-6860e9ac-110f-11e8-82d4-9f7fad7ba35f.png)

This will happen if I click on any of the errors:

![2018-02-13 4](https://user-images.githubusercontent.com/36000427/36172718-6f4c4342-110f-11e8-9914-2a390c9669e0.png)

If I use C/C++ with error squiggles, and make an obvious error, I can click on the error and it opens with no problem. This problem of not being able to click on errors to open files only persists with Flylint.

**Comment by jbenden** [comment]
Hello, version 0.5.5 has been published that resolves Windows file URIs.

Thanks,
-Joe
