### ISSUE TITLE
Inline files

### ISSUE THREAD

**Issue by VioletOil** [jbenden/vscode-c-cpp-flylint#32]
I'm separating my template class declaration and implementation into 2 files(The example is below). Is there a way to tell clang analyzer that this is not just independent cpp file, but it is a part of the header? Because it gives the enormous amount of errors and I can't properly use it.

foo.h:
```
template <typename T>
class foo
{
  public:
      void bar(T);
}
#include "foo.cpp"
```
foo.cpp:
```
template <typename T>
void foo<T>::bar(T var)
{
   //Implementation
}
```

**Comment by jbenden** [comment]
This is not an issue with the analyzers, but rather an odd use of C++. I'd recommend approaching this by clever use of defines and includes, to permit the `.cpp` file to see the definition of class `foo`.
