### ISSUE TITLE
cppcheck template doesnt work (on Windows?)

### ISSUE THREAD

**Issue by pipijajko** [jbenden/vscode-c-cpp-flylint#37]
https://github.com/jbenden/vscode-c-cpp-flylint/blob/4da6913182d4dcb3f9c7e766ae84fa01162bfb91/c-cpp-flylint-server/src/linters/cppcheck.ts#L56

Without additional quotation marks for the whole --template string, Cppcheck 1.83. will only print filename.

**Comment by jbenden** [comment]
[c-cpp-flylint-0.6.0-window-escaping-fix.zip](https://github.com/jbenden/vscode-c-cpp-flylint/files/1948366/c-cpp-flylint-0.6.0-window-escaping-fix.zip)

Would you mind trying this test extension? It should fix your reported problem, but I want to ensure it works before publishing a full update.

[Instructions for installing an extension from a VSIX file](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)

**Comment by jbenden** [comment]
Problem should be resolved in the latest version, just published.

Best regards,
-Joe
