### ISSUE TITLE
onType linting very slow.

### ISSUE THREAD

**Issue by ryan27968** [jbenden/vscode-c-cpp-flylint#39]
Hello there.
So basically onType linting is pretty slow. You have to stop typing for about 4 seconds before it'll lint. I'm not sure if this is a VSCode issue or not, but either way it pretty much defeats the object of ontype linting.  Have you run into this problem and do you have any remedys?

**Comment by jbenden** [comment]
Hello,

The tools (linters) are simply pretty slow. The only measures to improve speed are typical ones, such as everything on SSD, etc.

Best regards,
-Joe

**Comment by jbenden** [comment]
Problem should be resolved in the latest version, just published.

Best regards,
-Joe
