### ISSUE TITLE
.clang_complete doesn't work

### ISSUE THREAD

**Issue by stunpix** [jbenden/vscode-c-cpp-flylint#4]
AFAIK .clang_complete never been a part of clang configuration and it used only by vim/emacs plugins, so it never autoloaded by clang. Plugin should implement read out of all options from .clang_complete and pass them to clang as command line arguments or any clang_complete options must be removed from configuration, since they aren't working.

Why not to do even better: read all project settings (include dirs, defines, etc) from .vscode/c_cpp_properties.json which usually already configured in c++ projects?

**Comment by jbenden** [comment]
An update has been published that adds the `c_cpp_properties.json` functionality.

-Joe
