### ISSUE TITLE
Error: links in the problem tab don't work anymore (Windows)

### ISSUE THREAD

**Issue by cplussharp** [jbenden/vscode-c-cpp-flylint#43]
If I click on a problem in the `PROBLEMS` tab I get the following error message:

> Unable to open 'Test.cpp': File not found (file:///c:/Development/Project"c:/Development/Project/Subfolder/Test.cpp).

The text right to the file node in the problem tab is also wrong:
`"c:\Development\Project\Subfolder"` should be just `"Subfolder"`

**Comment by jbenden** [comment]
I'm not sure where in this the code appends the entire path again... Hum.

Could you post your project to this ticket, as a ZIP file? It would help me to debug this matter.

Thanks!

**Comment by cplussharp** [comment]
Sorry can't past my project, it is a little to big (> 25.000 cpp/h files) and closed source.
I will try to create a sample project.

**Comment by cplussharp** [comment]
OK even with a really simple test project the problem path is wrong.

I just created a file main.cpp in an empty folder, and opened vscode in this folder. CppCheck was used for the linting.

Content of main.cpp:
```C++
#include <iostream>

int main()
{
    int x = 5;
    std::cout << "Hello World!" << std::endl;
    return 0;
}
```

**Comment by cplussharp** [comment]
Ah I found the problem (for both bugs)! This is my log output:

```
[ '"c:\\Temp\\Test\\main.cpp  5  style unreadVariable: Variable \'x\' is assigned a value that is never used."',
  '"    information missingIncludeSystem: Cppcheck cannot find all the include files (use --check-config for details)"',
  '' ]
```
The linter gets the cppcheck output lines in quotation marks!

I'm not sure where this should be fixed in linter::lint() or linter::parseLines() or in the parseLine() of the linter (e.g. cppcheck::parseLine())

**Comment by jbenden** [comment]
Would you mind testing the master branch, at at least commit bdb40aa? I am hoping this resolves our problem.

**Comment by cplussharp** [comment]
Yes, this change resolves the problem. Thanks again.

**Comment by jbenden** [comment]
Thanks!
