### ISSUE TITLE
too many errors to make parse error 

### ISSUE THREAD

**Issue by xiaoyongdong** [jbenden/vscode-c-cpp-flylint#45]
![image](https://user-images.githubusercontent.com/3884211/41921403-5d9acb34-7995-11e8-931b-3974a3dd78cf.png)

**Comment by jbenden** [comment]
This is not related to the extension, but rather to missing compiler configuration. Please see the guide on setting up VS Code for C/C++ projects.

**Comment by xiaoyongdong** [comment]
I mean that this condition may be make the extension parse failed.
![image](https://user-images.githubusercontent.com/3884211/41923736-d1f08618-799a-11e8-8c05-dbf7c32a981d.png)
