### ISSUE TITLE
bug report: continuous warning of "incompatible with c++98"

### ISSUE THREAD

**Issue by yxtj** [jbenden/vscode-c-cpp-flylint#46]
I have installed clang and cppcheck as checkers. I have already set `"c-cpp-flylint.clang.standard": ["c++11", "c++14", "c++17"]` and `"c-cpp-flylint.cppcheck.standard": ["c++11"]` in my settings.json file.
But every time I save a file I get a warning notification like below. There is no problem in building the project. It only appears in the static analysis.
I am using Ubuntu 18.04 with VS Code 1.25.1. 

------

vscode-c-cpp-flylint: 'Line could not be parsed: warning: 'auto' type specifier is incompatible with C++98 [Semantic Issue]' while validating: /home/<xxxx>/Code/XXXX/src/runner/Master_handler.cpp. Please analyze the 'C/C++ FlyLint' Output console. Stacktrace: Error: Line could not be parsed: warning: 'auto' type specifier is incompatible with C++98 [Semantic Issue] at lines.forEach.line (/home/<xxxx>/.vscode/extensions/jbenden.c-cpp-flylint-1.1.1/server/linters/linter.js:221:31) at Array.forEach (native) at Clang.parseLines (/home/<xxxx>/.vscode/extensions/jbenden.c-cpp-flylint-1.1.1/server/linters/linter.js:205:15) at Clang.lint (/home/<xxxx>/.vscode/extensions/jbenden.c-cpp-flylint-1.1.1/server/linters/linter.js:195:21) at lintersCopy.forEach.linter (/home/<xxxx>/.vscode/extensions/jbenden.c-cpp-flylint-1.1.1/server/server.js:242:43) at Array.forEach (native) at /home/<xxxx>/.vscode/extensions/jbenden.c-cpp-flylint-1.1.1/server/server.js:239:21 at Generat...

**Comment by jbenden** [comment]
For `"c-cpp-flylint.clang.standard"`, try only setting a single entry; such as `c++17`.

**Comment by yxtj** [comment]
@jbenden It does not work. That is why I set multiple.

**Comment by jbenden** [comment]
I've just pushed a new version of the extension which should solve this conundrum.

Thank you for your patience,
-Joe

**Comment by yxtj** [comment]
Thanks Joe. I will try it once it is available.

**Comment by Ryngetsu** [comment]
Hello Joe, I have the same bug and it doesn't go away.

By the way, I had a hard time configuring it on Windows. Maybe you should write how to do it somewhere.

When I set "c-cpp-flylint.clang.standard": "c++17" it doesn't even work, it's an error.
And when I do "c-cpp-flylint.clang.standard": ["c++17"], it gives the bug stated above.

Thank you

**Comment by eckschi** [comment]
Hmm, your fix seems to only skip messages that have a string containing "incompatible", it doesn't really change the standard of the linter.

**Comment by j-m** [comment]
I also have this issue. Any news?

**Comment by laczika** [comment]
Same problem here.

**Comment by linonetwo** [comment]
Try `"c-cpp-flylint.clang.extraArgs": ["-Wno-c++98-compat"],`

**Comment by Todd-Fulton** [comment]
also try `"no-c++98-compat-pedantic"`
https://clang.llvm.org/docs/DiagnosticsReference.html#id120

with `-Weverything` you need to "black-list" warnings that don't apply (too noisy), instead of "white-listing" the warnings you want. I believe the default is `["all", "extra", "everything"]` prolly why you get c98 compat warnings in c++17 mode.
