### ISSUE TITLE
error : line could not be parsed

### ISSUE THREAD

**Issue by camelator** [jbenden/vscode-c-cpp-flylint#47]
Hi,
Please note the issue I have with my source code:

Here is the message displayed in the window:
vscode-c-cpp-flylint: 'Line could not be parsed: (information) Couldn't find path given by -I '/home/christian/Documents/monrobot/testcmake7/**/'' while validating: /home/christian/Documents/monrobot/testcmake7/src/mygl/core/baseEngine.h. Please analyze the 'C/C++ FlyLint' Output console. Stacktrace: Error: Line could not be parsed: (information) Couldn't find path given by -I '/home/christian/Documents/monrobot/testcmake7/**/'
    at lines.forEach.line (/home/christian/.vscode/extensions/jbenden.c-cpp-flylint-1.2.0/server/linters/linter.js:221:31)
    at Array.forEach (<anonymous>)
    at CppCheck.parseLines (/home/christian/.vscode/extensions/jbenden.c-cpp-flylint-1.2.0/server/linters/linter.js:205:15)
    at CppCheck.lint (/home/christian/.vscode/extensions/jbenden.c-cpp-flylint-1.2.0/server/linters/linter.js:195:21)
    at lintersCopy.forEach.linter (/home/christian/.vscode/extensions/jbenden.c-cpp-flylint-1.2.0/server/server.js:242:43)
    at Array.forEach (<anonymous>)
    at /home/christian/.vscode/extensions/jbenden.c-cpp-flylint-1.2.0/server/server.js:239:21
    at Generator.next (<anonymous>)
    at fulfilled (/home/christian/.vscode/extensions/jbenden.c-cpp-flylint-1.2.0/server/server.js:4:58)
    at <anonymous>

**Comment by jbenden** [comment]
The problem is caused by an include path failing.

**Comment by camelator** [comment]
I juste use cmake tools. If my program compiling Well... So there is a gap between the tools

**Comment by jbenden** [comment]
This extension requires that either the standard `c_cpp_properties.json` file has been set up, or that all relevant settings are set in the workspace configuration. I'm sorry it didn't meet your needs.

**Comment by krash84** [comment]
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json",
            "configurationProvider": "vector-of-bool.cmake-tools"
        }
    ],
    "version": 4
}
```

What's wrong with this setup?

**Comment by jbenden** [comment]
The plugin passes the paths directly to the tools - patches welcomed!

**Comment by hyoretsu** [comment]
At least let us supress this, everythin's working fine and the error only started popping up after setting up CMake.

**Comment by CoreyCole** [comment]
Path glob handling is being discussed in #144 https://github.com/jbenden/vscode-c-cpp-flylint/issues/144
