### ISSUE TITLE
error:Unable to run extension.

### ISSUE THREAD

**Issue by yaoyiqun** [jbenden/vscode-c-cpp-flylint#49]
Hi.I am attempting to run clang using your extension.
c_cpp_properties.json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/inc/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
settings.json:

 "c-cpp-flylint.flexelint.enable": false,
    "c-cpp-flylint.cppcheck.force": true,
    "C_Cpp.default.cppStandard": "c++11",
    "C_Cpp.default.intelliSenseMode": "clang-x64",
    "c-cpp-flylint.clang.executable":"clang"

but not any message console area for all C/C++ Flylint output. 
and if i use  ctrl+shift+p to run "c/c++ Flylint:Analyze" command,  
 I get the error: command 'c-cpp-flylint.analyze*' not found

**Comment by jbenden** [comment]
Hi, I believe you have a configuration issue.

First, you have `cppcheck` enabled but not `clang`. Please enable Clang. Eg:

```
{
    "c-cpp-flylint.clang.enable": true,
    "c-cpp-flylint.clang.executable": "clang-4.0",
    "c-cpp-flylint.run": "onType",
    "c-cpp-flylint.flexelint.enable": false,
    "c-cpp-flylint.cppcheck.enable": false,
    "c-cpp-flylint.debug": true
}
```

Do note that `cppcheck` is very slow. I'd recommend the other analyzers supported.

-Joe

**Comment by yaoyiqun** [comment]
> Hi, I believe you have a configuration issue.
> First, you have cppcheck enabled but not clang. Please enable Clang. Eg:
> {
>     "c-cpp-flylint.clang.enable": true,
>     "c-cpp-flylint.clang.executable": "clang-4.0",
>     "c-cpp-flylint.run": "onType",
>     "c-cpp-flylint.flexelint.enable": false,
>     "c-cpp-flylint.cppcheck.enable": false,
>     "c-cpp-flylint.debug": true
> }
> 
> Do note that cppcheck is very slow. I'd recommend the other analyzers supported.
> -Joe

yes,this solve the problem,thanks
