### ISSUE TITLE
Not loading cppcheck properly

### ISSUE THREAD

**Issue by hari-nd** [jbenden/vscode-c-cpp-flylint#56]
Issue Type: <b>Bug</b>

Check cppcheck problems reported are navigatable.

Extension version: 1.2.4
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 1028)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.67GB (0.61GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by hariseenivasan** [comment]
When I click on the window where it's reported. It's removing all the entries in that window.

**Comment by jbenden** [comment]
The latest extension version should not have this problem any more.
