### ISSUE TITLE
Static analyzers should include all workspace directories

### ISSUE THREAD

**Issue by burillo-se** [jbenden/vscode-c-cpp-flylint#59]
When clang analyzer is run, it doesn't include the workspace directories. This assumes that the source code headers are always in the same directory as file, which isn't always the case. With a project that's organized into multiple directories and has headers all over the place, specifying the directories in settings.json is not a good option because the list of directories is just so huge.

Therefore, clang (and others) should include the recursive list of workspace directories by default, or at least have an option to do so.

**Comment by burillo-se** [comment]
I've attempted to add this functionality myself (how hard can a directory recursion be?!), but i'll have to admit that i don't know what i'm doing around VSCode, NPM and all of this JS ecosystem that is alien to me. Testing the extension seems to be a problem - i can't even run the original extension in debug mode, let alone a modified one, and VSCode wouldn't tell me what's wrong ("9" is not a helpful error message).

So i guess i'll have to live without clang code analyzer for now, and hope that some day, you will add this :)

**Comment by jbenden** [comment]
In the `master` branch, changes were made to fix excluded paths; however, this should be now possible using a combination of glob inside include paths of `c_cpp_properties.json`, and using `c-cpp-flylint.excludeFromWorkspacePaths` for any paths that shouldn't be in the set.
