### ISSUE TITLE
Messages like “Unable to activate XX analyzer”

### ISSUE THREAD

**Issue by AndersBillLinden** [jbenden/vscode-c-cpp-flylint#6]
When I with vscode 1.14.1 in Windows 10 pro add the following extensions:

* C/C++ 0.12.0
* C/C++ Advanced List 0.2.3
* C/C++ Clang Command Adapter 0.2.2
* C# 1.11.0
* C++ Intellisense 0.2.2
* Code Runner 0.6.26
* Debugger for Chrome 3.1.6
* Git History (git log) 0.2.1

opening a C file will result in a dropdown with the following messages:

* Unable to activate Flexelint analyzer.
* Unable to activate CppCheck analyzer.
* Unable to activate Clang analyzer.

The error messages will not go away and appears every time I switch to an editor with a file with that extension.

* There are no clues on why those "analysers" could not be "activated".
* The error message reappears every time a file with some extension instead of only informing the user once.
* The error messages are partly covering the editor.
* There is no way to close a single line, the close button on each line has to be clicked.

Screenshots on https://stackoverflow.com/questions/45160650/why-do-i-get-error-messages-like-unable-to-activate-xx-analyzer-in-vscode

**Comment by jbenden** [comment]
Hello,

Firstly, if you do not have any of the analyzers installed; they simply cannot work. In this case, explicitly disable the ones you do not have installed in your user settings (see `c-cpp-flylint.<analyzer>.enable` flags.)

Secondly, if the analyzers are not configured, they won't work. Either configure the ones you desired or see above on disabling the ones you do not wish to utilize.

On an aside: If the C file you are opening is not contained within a work space; then the analyzers typically won't work; however, see the above two for more information.

Finally, under the Output view, there is a drop-down to select a source. Select the C/C++ Flylint source and you will see a wealth of debugging information useful to both of us, if you still experience problems.
