### ISSUE TITLE
Cannot see the debug output

### ISSUE THREAD

**Issue by xiaoyongdong** [jbenden/vscode-c-cpp-flylint#60]
I have already set c-cpp-flylint.debug: true
But i can not see anything on output window.
![image](https://user-images.githubusercontent.com/3884211/62684114-8ec4d800-b9f2-11e9-9fd5-2baa98376d2e.png)

**Comment by romange** [comment]
Hi @jbenden  I can not see either. What are we missing?

**Comment by aidandj** [comment]
+1, cannot see the output.

**Comment by jbenden** [comment]
Hello,

What version of VS Code are you running, and on which platform?

Thanks,
-Joe
