### ISSUE TITLE
Add trigger on build (bug on Clang)

### ISSUE THREAD

**Issue by X-Ryl669** [jbenden/vscode-c-cpp-flylint#61]
I've large and complex C++ code and currently, even if the option to run the linter is set to "onSave", it's running Clang linting every char I'm typing (so it's very slow).

Cppcheck seems to run on saving, but it's taking eons to finish.

Would it be possible to add a trigger on build (instead of "onSave") so I can decide when to lint instead of struggling with a slow system that's linting obsolete code ?

**Comment by marcomeyerVFX** [comment]
I have the same experience with clang, even though it's also getting sluggish to write code when only cppcheck is enabled.
I would even suggest adding a "manual" linting trigger, so linting can be triggered only through one of the Command Palette options. 

Right now, I can only disable flylint completely in the settings with `c-cpp-flylint.enable` however this obviously also affects the linting trigger through the Command Palette and throws an error:
```
Command 'C/C++ Flylint: Analyze the active document' resulted in an error (command 'c-cpp-flylint.analyzeActiveDocument' not found)
```

**Comment by X-Ryl669** [comment]
Thanks!
