### ISSUE TITLE
Cppcheck standard flag is not working

### ISSUE THREAD

**Issue by DatJohnny** [jbenden/vscode-c-cpp-flylint#65]
Visual Studio Code Version: 1.40.1
OS: Linux x64 5.3.11-200.fc30.x86_64
C/C++ Advanced Lint Version: 1.2.4

I have problem with cppcheck standard flag:
![image](https://user-images.githubusercontent.com/28908121/69495269-583d9b00-0ec5-11ea-8c44-30fbba46d4b3.png)
![image](https://user-images.githubusercontent.com/28908121/69495274-6c819800-0ec5-11ea-8d4a-8c987f6c5209.png)
Temporary workaround: put "--std=c++11" flag into cppcheck executable path.

**Comment by stjen** [comment]
c-cpp-flylint.cppcheck.standard expects an array of standards to check against, thus your setting should look like:
"c-cpp-flylint.cppcheck.standard": ["c++11"]

**Comment by DatJohnny** [comment]
Uh.. It works. Thanks!
