### ISSUE TITLE
Support for muting the warnings 

### ISSUE THREAD

**Issue by sonulohani** [jbenden/vscode-c-cpp-flylint#72]
I am using this extension in my work environment however due to large number of files in the project the extension provides a warning in timely manner which is sometimes very frustrating.  Could you please provide a way to mute the warnings from flylint so that I don't have to close the warning dialogue box every time.

**Comment by jbenden** [comment]
Hello,

Are you looking to pause linting, leaving the existing list of warnings in place? Or am I misunderstanding your request?

Thanks,
-Joe

**Comment by sonulohani** [comment]
Hi @jbenden 

Please close this issue. Doesnt seem like issue anymore.

**Comment by jbenden** [comment]
Ok, please re-open if needed!
