### ISSUE TITLE
Allow separate settings for C and C++

### ISSUE THREAD

**Issue by LinAGKar** [jbenden/vscode-c-cpp-flylint#74]
Currently, this checks all files as C++, or all files as C, regardless of what language the file is in. Instead, it should check C files as C and C++ files as C++, and allow separate warnings by language.

**Comment by jbenden** [comment]
Hello,

Thank you for the suggestion; however, the configuration of the C++ extension of VS Code does not have this separation between languages, and this extension reads from it.

**Comment by LinAGKar** [comment]
The C/C++ extension definitely handles the languages differently.  C++ syntax gives an error in C files and not in C++ files, and there are separate cStandard and cppStandard settings.
