### ISSUE TITLE
Support Extra Args for cppcheck

### ISSUE THREAD

**Issue by Tradias** [jbenden/vscode-c-cpp-flylint#76]
Similar to

> Clang: Extra Args
> Extra verbatim command-line arguments to include on the Clang command-line invocation.

provide an option to configure "Extra Args" that will be passed to cppcheck, To give some background, I am trying to set the "--project" flag of cppcheck which can point to e.g. a "compile_commands.json" that contains all the includes and defines of the project.

I am not familiar with Flexelint but I can image that providing a similar configuration option for it might make sense as well.

**Comment by dwlsalmeida** [comment]
Try providing a config file for the project via cppcheck-gui

You can specify the compilation database (compile_commands.json) there

I think either the addon or cppcheck itself will look for a config file

**Comment by dwlsalmeida** [comment]
me too
