### ISSUE TITLE
Cppcheck - Support for c++14 / c++17 standards

### ISSUE THREAD

**Issue by rnd-debug** [jbenden/vscode-c-cpp-flylint#77]
Hello,
it seems (server/src/linters/cppcheck.ts) that c14 / c17 standards are not part of the "allowedStandards" for cppcheck.
Would it be possible to allow them? 
[Edit] if it can help, here are the release notes of cppcheck: https://github.com/danmar/cppcheck/releases

**Comment by jbenden** [comment]
Thanks for the report!

**Comment by rnd-debug** [comment]
Thx! Really appreciated!
For the things to be even more beautiful, can you also fix the extension's docs?
(you updated the clang part in the docs, instead of the part concerning cppcheck):
https://github.com/jbenden/vscode-c-cpp-flylint/blob/a57b6e9c9b83c17ba9f243d6ff79fdeb8d853873/client/package.json#L344-L351
