### ISSUE TITLE
Can't debug server with current README instructions

### ISSUE THREAD

**Issue by dwlsalmeida** [jbenden/vscode-c-cpp-flylint#79]
Breakpoints do not work, instead I get this message "Breakpoint ignored because generated code not found (source map problem?)"

I am new to the JS ecosystem...any tips?

Thanks

**Comment by jbenden** [comment]
I'm not sure... I had this working on Ubuntu 16.04. However, I've switched distros since then.

What OS and version are you trying to debug on?

**Comment by jbenden** [comment]
Hello,

The latest sources should have a working debug. I am launching a test instance using F5 within the project.

Thanks,
-Joe

**Comment by jbenden** [comment]
Hello,

The debugging is still broken. It occurred after adding webpack to the mix. I've tried some things, but still cannot get this working.

If anybody knows how to fix this, we'd all be grateful!

Thanks,
-Joe
