### ISSUE TITLE
Need documentation on how to suppress certain warnings

### ISSUE THREAD

**Issue by nitishingde** [jbenden/vscode-c-cpp-flylint#80]
For example:
I am using cppcheck as my linter. I want to suppress certain warnings "nested namespace definition is a C++17 extension; define each namespace separately ccls(4)".

**Comment by jbenden** [comment]
Hello,

The information you are looking for is found in the tools themselves; namely in `cppcheck` for instance. This extension just calls out to these other tools, parses their output, and displays the diagnostics inside VS Code.

Best regards,
-Joe
