### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by gomal** [jbenden/vscode-c-cpp-flylint#81]
[jbenden.c-cpp-flylint-unresponsive.cpuprofile.txt](https://github.com/jbenden/vscode-c-cpp-flylint/files/4828219/jbenden.c-cpp-flylint-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `c-cpp-flylint`
- Extension Version: `1.4.4`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.46.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\sonda\jbenden.c-cpp-flylint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jbenden** [comment]
Hello,

Would you mind trying the PR #82 to see if performance improves for you?

Thanks!
-Joe
