### ISSUE TITLE
Unable to get extension to work on a Mac

### ISSUE THREAD

**Issue by aunitt** [jbenden/vscode-c-cpp-flylint#88]
I'm trying to get this extension to work on my Mac with no success.

When opening a cpp file I get the following error:

vscode-c-cpp-flylint: 'Line could not be parsed: warning: include location '/usr/local/include' is unsafe for cross-compilation' while validating: /Users/ashley.unitt/xxx/xxx.cpp. Please analyze the 'C/C++ FlyLint' Output console. Stacktrace: Error: Line could not be parsed: warning: include location '/usr/local/include' is unsafe for cross-compilation at /Users/ashley.unitt/.vscode/extensions/jbenden.c-cpp-flylint-1.5.1/dist/server/server.bundle.js:39:75886 at Array.forEach (<anonymous>) at s.parseLines (/Users/ashley.unitt/.vscode/extensions/jbenden.c-cpp-flylint-1.5.1/dist/server/server.bundle.js:39:75620) at s.lint (/Users/ashley.unitt/.vscode/extensions/jbenden.c-cpp-flylint-1.5.1/dist/server/server.bundle.js:39:75523) at /Users/ashley.unitt/.vscode/extensions/jbenden.c-cpp-flylint-1.5.1/dist/server/server.bundle.js:138:6706 at Array.forEach (<anonymous>) at /Users/ashley.unitt/.vscode/extensions/jbenden.c...

In the C/C++ Flylint output window I get:
Performing lint scan of /Users/ashley.unitt/xxx/xxx.cpp...
Skipping Clang linter because lintOn 3 is not in 2.
Skipping CppCheck linter because lintOn 1 is not in 2.
Skipping Flexelint linter because lintOn 1 is not in 2.
Completed lint scans...

I have Clang enabled and I've also tried installing CppCheck using homebrew

This is on Catalina version 10.15.7

**Comment by jbenden** [comment]
Hi,

I do not have access to a macOS machine at this time, so I am unable to help in a complete manner. However, I notice that the first error message expelled from Clang is about cross-compilation. So one of two things is most probable: a. you've not specified a complete set of arguments to Clang for a non-cross-compilation, or b. you've not specified the correct headers and libraries for cross-compilation. For the later, [this](https://stackoverflow.com/questions/23248989/clang-c-cross-compiler-generating-windows-executable-from-mac-os-x) may help.

The key is to **first** be able to build from Terminal, then make your IDE work... It's easiest this way.

Best regards,
-Joe

**Comment by aunitt** [comment]
I have got this building from the Terminal and in the IDE and I'm not attempting to do a cross-compile.

I get the lint error on a very simple helloworld app:

#include <iostream>

using namespace std;

int main()
{
    cout << "Hello World!" << endl;
}

Compiling in a terminal with: clang++ --std=c++17 -g main.cpp -o main

**Comment by aunitt** [comment]
Sorry, the above mangled the code slightly, it should be:

`#include <iostream>

using namespace std;

int main()
{
    cout << "Hello World!" << endl;
}`

**Comment by jbenden** [comment]
You might try debugging the flags passed to the linter, and double-check that the correct binaries are used.

**Comment by aunitt** [comment]
I've done some more digging and I think I understand the problem.
By default, the extension sets warnings for clang at "-Wall -Wextra -Weverything".
If you have -Weverything that includes -Wpoison-system-directories which causes the warning:
`
warning: include location '/usr/local/include' is unsafe for cross-compilation
      [-Wpoison-system-directories]
`
to be issued.
I think your extension has issues with parsing this warning and then fails.
I've changed my settings to include:
`
    "c-cpp-flylint.clang.warnings": ["all", "extra"]
`
and the extension now works.

Here is an example of the output that failed to parse:
`
The executable was not found for Flexelint; looked for flexelint
Performing lint scan of /Users/ashley.unitt/cpp-test-project/main.cpp...
executing:  /usr/bin/clang -fsyntax-only -fno-color-diagnostics -fno-caret-diagnostics -fno-diagnostics-show-option -fdiagnostics-show-category=name -ferror-limit=200 --std=c11 --std=c++11 -fblocks -Wall -Wextra -Weverything -I /Users/ashley.unitt/cpp-test-project/.vscode -I /Users/ashley.unitt/cpp-test-project/main.dSYM -I /Users/ashley.unitt/cpp-test-project/main.dSYM/Contents -I /Users/ashley.unitt/cpp-test-project/main.dSYM/Contents/Resources -I /Users/ashley.unitt/cpp-test-project/main.dSYM/Contents/Resources/DWARF -x c++ /Users/ashley.unitt/cpp-test-project/main.cpp
[ '' ]
[
  "warning: include location '/usr/local/include' is unsafe for cross-compilation",
  '/Users/ashley.unitt/cpp-test-project/main.cpp:8:2: warning: C++98 requires newline at end of file [Lexical or Preprocessor Issue]',
  ''
]
`

**Comment by jbenden** [comment]
Thank you for the feedback.

I am hesitant to make a change that ignores this warning, by default. I also like having the default at maximum warnings. However, having said that - what are your thoughts on this? Should any change be made?

Thank you!
-Joe

**Comment by aunitt** [comment]
I think the minimum is to fix the bug so your parsing of the warning "warning: include location '/usr/local/include' is unsafe for cross-compilation" works.

My personal view is that -Weverything is not the best idea as it includes experimental warnings. I would go for -Wall -Wextra. This if from reading the [clang docs on -Weverything](https://clang.llvm.org/docs/UsersManual.html#diagnostics-enable-everything).

That's just a personal view. I think -Weverything is valid, you just need to balance that tradeoff of being on the bleeding edge of getting more warnings but being less sure of their validity.

**Comment by jbenden** [comment]
Thank you for your feedback. After review, I did make both changes.

Thanks again!
-Joe

**Comment by aunitt** [comment]
Thanks!
