### ISSUE TITLE
Pls add option --include to cppcheck

### ISSUE THREAD

**Issue by Setius2** [jbenden/vscode-c-cpp-flylint#95]
cppcheck has the option --include=<file> (force the file to be included before the file being checked.).
But this option is not implemented in the flylint

**Comment by jbenden** [comment]
Hello,

There is a configuration settings for extra argument, where this option should be able to go. See:

```
{
  "c-cpp-flylint.cppcheck.extraArgs": [
    "--include", "...file..."
  ]
}
```

Best regards,
-Joe

**Comment by Setius2** [comment]
Thanks.
I didn't notice the `c-cpp-flylint.cppcheck.extraArgs` option.
