### ISSUE TITLE
The C/C++ Flylint server crashed

### ISSUE THREAD

**Issue by Hairy-Lee** [jbenden/vscode-c-cpp-flylint#96]
Hi 

1st off, thanks for releasing v1.7.1. I've been using it this morning and have had 3 instances so far where I have recieved the following notification:

`The C/C++ Flylint server crashed 5 times in the last 3 minutes. The server will not be restarted.`

The main issues seem to be:

`Error: EBUSY: resource busy or locked, lstat 'c:\DumpStack.log.tmp'`
`Error: EPERM: operation not permitted, lstat 'c:\$Recycle.Bin\S-1-5-18'`

Here is the full output

[output.txt](https://github.com/jbenden/vscode-c-cpp-flylint/files/5808114/output.txt)

If I close VS Code and then reopen it then it rights itself.

**Comment by jbenden** [comment]
Hello,

Sorry to hear this!

After some research, your problems are originating from the NPM `chokidar`, and somehow relate to a bad path being used to watch files... See [here](https://github.com/paulmillr/chokidar/issues/1037) for more about it.

I am not sure what is causing it, but posting your config may help...

Thanks,
-Joe

**Comment by Hairy-Lee** [comment]
Hi Joe

Thanks for your response. Please forgive my ignorance, but JS is not something I am acqainted with. I've updated node.js and npm and I haven't observed the issue again...yet :o|

Do I need to have `chokidar` installed? Also, specifically which config would you want me to post should I observe the issue again? The flylint settings.json?

Thanks,

HL

**Comment by jbenden** [comment]
Sorry on the delay... If everything is currently working, then there is nothing more we need to do! Also, you do not need to install `chokidar`, nor post your configuration.

I appreciate all the help you've provided during development of this new analyzer module.

Thank you very much!
-Joe
