### ISSUE TITLE
cppcheck not analysing on file open

### ISSUE THREAD

**Issue by bbennetts** [jbenden/vscode-c-cpp-flylint#98]
Hi,

Having cppcheck analyse on file save or typing is not as useful as doing an initial scan on file open.  Is there a way to enable this, if not is it possible to introduce one?

TIA.

**Comment by jbenden** [comment]
Hello,

I thought it does scan on initial file open;  when:
1. the workbench is first opened.
2. on the file being initially opened.
 
Does this not work? Or is there another condition when it should scan?

Thanks!
-Joe

**Comment by bbennetts** [comment]
Ok, so my mistake - it *is* running cppcheck although it is taking quite a long time to start.  It does not appear in the log drop down for quite some time (are the various extensions queued, rather than parallel?).   However, with debug logging on it shows that errors are being found, but then it is quitting due to the lintOn state which I believe is set to "On Save".  I'll attach a log all text in <CAPS> is placeholder text.

[linterrs.txt](https://github.com/jbenden/vscode-c-cpp-flylint/files/5872344/linterrs.txt)

**Comment by jbenden** [comment]
This specific analyzer is super slow, although with some settings can be made a bit faster.

All linters do not run in parallel, unfortunately. I'd love it if they did, though! It's been a feature I've been thinking about for a while now, but requires a lot of rework that I've been hesitant to make.

Thanks for the bug report. Let me know if anything else crops up!
-Joe
